### PR TITLE
WIP: fix #17

### LINKED ISSUE #17: Add ARM build?
Hello,

Is it fairly straightforward to make this also build an ARM64 image?

Cheers

### PR DESCRIPTION
**Pull request by LuckyTurtleDev**
This does create a multi platform image. Currently the element version is hard coded.
So we need to adjust the update program.
Their are two option:
* using a global env at the ci yml file and updating it per program
* loading the version from file and update the file

### CODE REVIEW

**Comment by bertybuttface** [comment]
Nice work on this! Loading from a file seems more sensible to me, that way the Dockerfile still works without CI.

**Comment by LuckyTurtleDev** [comment]
> that way the Dockerfile still works without CI.

No, it will not. Everything will be build with github actions and will be only copied to docker. This is necessary, because docker buildx/qemu cross platform build is very slow.

**Comment by msrd0** [comment]
I don't like this change. I would like to retain the ability to build the docker image locally. Otherwise, debugging any problems that might appear in the future is basically impossible.

**Comment by LuckyTurtleDev** [comment]
The alternative would be to build ever thing inside docker. but this would probably take 1 or 2 hours bulidtime.

This would also limit the supported architectur to 386 amd64 arm/v7 and arm64/v8. Probably less to avoid hitting the 2h runtime limit.

**Comment by msrd0** [comment]
GitHub has no such thing as a runtime limit. Building a cross-compiling Rust toolchain for AlpineLinux takes roughly 3 hours which is perfectly fine with github: https://github.com/msrd0/docker-abuild-arm/actions.

Limiting architectures to ones people reasonably use with servers these days (amd64, aarch64 and maybe armv7) is fine with me. We can always add more when people request it.

Also, we might not need to use docker to build an ~~docker~~ OCI image - it is an open standard these days. I have never used any alternative, but it might be worth exploring one.

**Comment by LuckyTurtleDev** [comment]
I would keep support for armv7. The raspberry 3 ist still popular.

**Comment by msrd0** [comment]
the raspberry pi 3 can run aarch64. just those idiots installing raspbian (granted, that is recommended by many tutorials) can't make use of the full capabilities.

**Comment by LuckyTurtleDev** [comment]
Since installing raspbian is much easier, there should be many "idiots".

I am as example still use some raspberys 2 as server.

**Comment by LuckyTurtleDev** [comment]
Closed, because the multiarch branch looks much better.

**Pull request closed without merging**
